name: medshield
description: "MedShield for team thyroes"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  device_preview: ^1.2.0
  path_provider: ^2.1.5
  csv: ^6.0.0
  share_plus: ^10.1.4
  http: ^1.3.0
  firebase_database: ^11.3.4
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
